name                = Crypt-JWS-OpenSSL
author              = Mark Dootson <mdootson@cpan.org>
license             = Perl_5
copyright_holder    = Mark Dootson
version             = 0.004

[GatherDir / lib]
root                = ../source-main/lib
prefix              = lib
exclude_match       = Crypt/JWS/OpenSSL/Local\.pm$

[GatherDir / inc]
root                = ../source-main/inc
prefix              = inc

[GatherDir / t]
root                = ../source-main/t
prefix              = t

[GatherFile]
root                = ../source-main
filename            = Changes
filename            = README

[PodSyntaxTests]

[RunExtraTests]

[MetaResources]
homepage          = https://metacpan.org/pod/Crypt::JWS::OpenSSL
bugtracker.web    = https://github.com/markdootson/crypt-jws-openssl-perl/issues
repository.url    = git://github.com/markdootson/crypt-jws-openssl-perl.git
repository.web    = https://github.com/markdootson/crypt-jws-openssl-perl
repository.type   = git

;[MakeMaker]
[MakeMaker::Awesome]
footer = package MY;
footer = sub postamble {
footer =     my $self = shift;
footer =     my $text = $self->SUPER::postamble // '';
footer =     
footer =     $text .= "\n\nconfig ::\n\t\$(PERLRUN) inc/do_postamble_action.pl\n\n";
footer =     return $text;
footer = }

[MetaJSON]

[MetaYAML]

[Manifest]

[CPANFile]

[License]

[AutoPrereqs]
skip = ^Crypt::JWS::OpenSSL::
skip = Crypt::OpenSSL::Guess
skip = lib
skip = ^Crypt::PK::
skip = Crypt::Perl
skip = ^Crypt::Perl::

[Prereqs / TestSuggests]
Crypt::PK::ECC                     = 0.069
Crypt::PK::RSA                     = 0.069
Crypt::Perl                        = 0.38

[Prereqs / ConfigureRequires]
Crypt::OpenSSL::Guess               = 0
